<template>
  <div class="contact">
    <ul>
      <li>
        Email:
        <a
          target="_blank"
          href="mailto:lev.kaplunov@yandex.ru"
        >
          lev.kaplunov@yandex.ru
        </a>
      </li>
      <li>
        Telegram:
        <a
          target="_blank"
          href="https://t.me/lev_kaplunov"
        >
          Lev Kaplunov
        </a>
      </li>
      <li>
        GitHub:
        <a
          target="_blank"
          href="https://github.com/lionlimon"
        >
          lionlimon
        </a>
      </li>
    </ul>
  </div>
</template>
